import styled from "styled-components";

const textStyles = StyleSheet.create({
  title40: {
    fontFamily: "Pretendard",
    fontSize: 40,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 50,
    letterSpacing: 0,
  },
  title32: {
    fontFamily: "Pretendard",
    fontSize: 32,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 40,
    letterSpacing: 0,
  },
  title24: {
    fontFamily: "Pretendard",
    fontSize: 24,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 30,
    letterSpacing: 0,
  },
  textB24: {
    fontFamily: "Pretendard",
    fontSize: 24,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 38.4,
    letterSpacing: 0,
  },
  text24: {
    fontFamily: "Pretendard",
    fontSize: 24,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 38.4,
    letterSpacing: 0,
  },
  title20: {
    fontFamily: "Pretendard",
    fontSize: 20,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 25,
    letterSpacing: 0,
  },
  textB20: {
    fontFamily: "Pretendard",
    fontSize: 20,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 32,
    letterSpacing: 0,
  },
  text20: {
    fontFamily: "Pretendard",
    fontSize: 20,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 32,
    letterSpacing: 0,
  },
  title18: {
    fontFamily: "Pretendard",
    fontSize: 18,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 22.5,
    letterSpacing: 0,
  },
  textB18: {
    fontFamily: "Pretendard",
    fontSize: 18,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 28.8,
    letterSpacing: 0,
  },
  text18: {
    fontFamily: "Pretendard",
    fontSize: 18,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 28.8,
    letterSpacing: 0,
  },
  title16: {
    fontFamily: "Pretendard",
    fontSize: 16,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 20,
    letterSpacing: 0,
  },
  botton16: {
    fontFamily: "Pretendard",
    fontSize: 16,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 24,
    letterSpacing: 0,
  },
  textB16: {
    fontFamily: "Pretendard",
    fontSize: 16,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 25.6,
    letterSpacing: 0,
  },
  checkbox16: {
    fontFamily: "Pretendard",
    fontSize: 16,
    fontWeight: "500",
    fontStyle: "normal",
    lineHeight: 16,
    letterSpacing: 0,
  },
  text16_STORY: {
    fontFamily: "Pretendard",
    fontSize: 16,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 28,
    letterSpacing: 0,
  },
  text16: {
    fontFamily: "Pretendard",
    fontSize: 16,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 25.6,
    letterSpacing: 0,
  },
  title14: {
    fontFamily: "Pretendard",
    fontSize: 14,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 17.5,
    letterSpacing: 0,
  },
  BUTTON_BUTTON_14: {
    fontFamily: "Pretendard",
    fontSize: 14,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 21,
    letterSpacing: 0,
  },
  textB14: {
    fontFamily: "Pretendard",
    fontSize: 14,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 22.4,
    letterSpacing: 0,
  },
  tag14: {
    fontFamily: "Pretendard",
    fontSize: 14,
    fontWeight: "500",
    fontStyle: "normal",
    lineHeight: 17.5,
    letterSpacing: 0,
  },
  checkbox14: {
    fontFamily: "Pretendard",
    fontSize: 14,
    fontWeight: "500",
    fontStyle: "normal",
    lineHeight: 14,
    letterSpacing: 0,
  },
  text14: {
    fontFamily: "Pretendard",
    fontSize: 14,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 22.4,
    letterSpacing: 0,
  },
  textB12: {
    fontFamily: "Pretendard",
    fontSize: 12,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 19.2,
    letterSpacing: 0,
  },
  text12: {
    fontFamily: "Pretendard",
    fontSize: 12,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 19.2,
    letterSpacing: 0,
  },
  text12_discountedPrice: {
    fontFamily: "Pretendard",
    fontSize: 12,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 19.2,
    letterSpacing: 0,
  },

  // caption
  caption: {
    fontFamily: "Pretendard",
    fontSize: 12,
    fontWeight: "500",
    fontStyle: "normal",
    lineHeight: 15,
    letterSpacing: 0,
  },

  // tag
  tag12: {
    fontFamily: "Pretendard",
    fontSize: 12,
    fontWeight: "500",
    fontStyle: "normal",
    lineHeight: 15,
    letterSpacing: 0,
  },
  tag10: {
    fontFamily: "Pretendard",
    fontSize: 10,
    fontWeight: "500",
    fontStyle: "normal",
    lineHeight: 12.5,
    letterSpacing: 0,
  },

  // fields
  fieldsB16: {
    fontFamily: "Pretendard",
    fontSize: 16,
    fontWeight: "700",
    fontStyle: "normal",
    lineHeight: 16,
    letterSpacing: 0,
  },
  fields16: {
    fontFamily: "Pretendard",
    fontSize: 16,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 16,
    letterSpacing: 0,
  },
  fields12: {
    fontFamily: "Pretendard",
    fontSize: 12,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 12,
    letterSpacing: 0,
  },
  fields10: {
    fontFamily: "Pretendard",
    fontSize: 10,
    fontWeight: "400",
    fontStyle: "normal",
    lineHeight: 10,
    letterSpacing: 0,
  },
});
